import Blogs from "@/components/pages/blogs/Blogs";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "StreetGrub | About",
  description: "Generated by streetGrub About page",
};
const BlogsPage = () => {
  return (
    <div>
      <Blogs />
    </div>
  );
};

export default BlogsPage ;
