import {
  Atom,
  Box,
  Braces,
  Cloud,
  Code2,
  Container,
  Cpu,
  Database,
  FileCode,
  GitBranch,
  Globe,
  Layers,
  Layout,
  Network,
  Package,
  Palette,
  Server,
  Share2,
  Shield,
  Smartphone,
  TestTube,
  Workflow,
  Zap,
} from "lucide-react";

/** Grouped to mirror resume “Core Skills” — levels reflect depth vs. secondary exposure */
export const skillCategories = [
  {
    title: "Languages & Core Frameworks",
    icon: Layout,
    skills: [
      { name: "JavaScript (ES6+)", level: 96, icon: Braces },
      { name: "TypeScript", level: 95, icon: Code2 },
      { name: "React", level: 96, icon: FileCode },
      { name: "Next.js", level: 94, icon: Zap },
      { name: "Redux", level: 92, icon: Layers },
      { name: "React Query", level: 92, icon: Workflow },
    ],
  },
  {
    title: "UI & Additional Frameworks",
    icon: Palette,
    skills: [
      { name: "Tailwind CSS", level: 91, icon: Palette },
      { name: "Bootstrap", level: 86, icon: Layout },
      { name: "Styled Components", level: 88, icon: Palette },
      { name: "Vue.js", level: 82, icon: Atom },
      { name: "Angular", level: 78, icon: Box },
      { name: "Svelte", level: 80, icon: Zap },
      { name: "Gatsby", level: 80, icon: Globe },
    ],
  },
  {
    title: "Rendering & Web Platform",
    icon: Globe,
    skills: [
      { name: "SSR / SSG / ISR", level: 94, icon: Server },
      { name: "Web Workers", level: 88, icon: Cpu },
      { name: "WebSockets", level: 90, icon: Network },
      { name: "PWA", level: 87, icon: Smartphone },
    ],
  },
  {
    title: "Backend & APIs",
    icon: Server,
    skills: [
      { name: "Node.js", level: 95, icon: Cpu },
      { name: "Express", level: 93, icon: Layers },
      { name: "NestJS", level: 90, icon: Server },
      { name: "Fastify", level: 86, icon: Zap },
      { name: "REST APIs", level: 94, icon: Share2 },
      { name: "GraphQL", level: 91, icon: Network },
      { name: "Apollo Server", level: 88, icon: Server },
      { name: "Apollo Client", level: 88, icon: Share2 },
      { name: "Socket.io", level: 89, icon: Network },
      { name: "Async & event-driven patterns", level: 92, icon: Workflow },
    ],
  },
  {
    title: "Data, Caching & Persistence",
    icon: Database,
    skills: [
      { name: "MongoDB", level: 93, icon: Database },
      { name: "PostgreSQL", level: 91, icon: Database },
      { name: "Redis", level: 91, icon: Zap },
      { name: "DynamoDB", level: 87, icon: Database },
      { name: "NoSQL modeling", level: 90, icon: Layers },
      { name: "Sharding & indexing", level: 92, icon: Workflow },
      { name: "Knex.js", level: 85, icon: FileCode },
      { name: "Sequelize", level: 84, icon: FileCode },
      { name: "Caching (Redis, ISR)", level: 92, icon: Zap },
    ],
  },
  {
    title: "AWS & Serverless",
    icon: Cloud,
    skills: [
      { name: "Lambda", level: 91, icon: Zap },
      { name: "ECS", level: 89, icon: Container },
      { name: "SQS", level: 87, icon: Workflow },
      { name: "RDS", level: 88, icon: Database },
      { name: "S3", level: 90, icon: Package },
      { name: "API Gateway", level: 88, icon: Network },
      { name: "CloudFormation", level: 85, icon: Layers },
      { name: "CloudWatch", level: 88, icon: Globe },
      { name: "Serverless Framework", level: 86, icon: Cloud },
    ],
  },
  {
    title: "DevOps, IaC & Delivery",
    icon: Container,
    skills: [
      { name: "Docker", level: 93, icon: Container },
      { name: "Kubernetes", level: 89, icon: Cloud },
      { name: "Terraform (IaC)", level: 87, icon: Layers },
      { name: "CI/CD — GitHub Actions", level: 91, icon: GitBranch },
      { name: "CI/CD — GitLab", level: 90, icon: GitBranch },
      { name: "CI/CD — Jenkins", level: 88, icon: GitBranch },
      { name: "Load balancing", level: 89, icon: Network },
    ],
  },
  {
    title: "Architecture & Security",
    icon: Shield,
    skills: [
      { name: "Microservices", level: 93, icon: Box },
      { name: "Event-driven systems", level: 92, icon: Workflow },
      { name: "Service mesh", level: 86, icon: Network },
      { name: "OAuth2", level: 88, icon: Shield },
      { name: "JWT", level: 90, icon: Shield },
    ],
  },
  {
    title: "Build, Test & Tooling",
    icon: Package,
    skills: [
      { name: "Webpack", level: 90, icon: Package },
      { name: "Vite", level: 91, icon: Zap },
      { name: "Parcel", level: 82, icon: Package },
      { name: "Babel", level: 88, icon: Code2 },
      { name: "Jest", level: 90, icon: TestTube },
      { name: "Mocha / Chai", level: 86, icon: TestTube },
      { name: "ESLint", level: 92, icon: FileCode },
      { name: "Prettier", level: 91, icon: FileCode },
      { name: "Axios", level: 93, icon: Share2 },
      { name: "RxJS", level: 84, icon: Workflow },
      { name: "Lodash", level: 88, icon: Layers },
      { name: "Moment.js / Day.js", level: 87, icon: Globe },
    ],
  },
];
