import Hero from "@/components/pages/home/Hero";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio Project | Home",
  description: "Generated by Portfolio Project Home page",
};

const HomePage = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Hero />
    </div>
  );
};

export default HomePage;
