import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio Project | Home",
  description: "Generated by Portfolio Project Home page",
};

const HomePage = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <main className="flex-grow">
        <div className=" max-w-7xl md:mx-auto mx-2 py-12"></div>
      </main>
    </div>
  );
};

export default HomePage;
