import BlogsPage from "@/components/pages/blogs/BlogsPage";
import ContactPage from "@/components/pages/contact/ContactPage";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Portfolio Project | About",
  description: "Generated by streetGrub Blogs page",
};
const Contact = () => {
  return (
    <div className="container mx-auto pt-8 md:px-6 px-2">
      <p>Blog PAGE ARE HERE</p>
      <ContactPage />
    </div>
  );
};

export default Contact;
