import ProjectsPage from "@/components/pages/projects/Projects";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Portfolio Project | Projects",
  description: "Generated by Portfolio Projects page",
};
const page = () => {
  return (
    <div>
      ProjectsPage
      {/* <ProjectsPage /> */}
    </div>
  );
};

export default page;
