import ProjectsPage from "@/components/pages/projects/StaticProjects";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Portfolio Project | Projects",
  description: "Generated by Portfolio Projects page",
};
const page = () => {
  return (
    <div className="py-24 px-4 max-w-7xl mx-auto">
      <p>
        {" "}
        ProjectsPage ProjectsPage ProjectsPage ProjectsPage ProjectsPage
        ProjectsPage{" "}
      </p>

      {/* <ProjectsPage /> */}
    </div>
  );
};

export default page;
