import ProjectsPage from "@/components/pages/projects/ProjectsPage";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Portfolio Project | Project",
  description: "Generated by Portfolio Project  page",
};
const Contact = () => {
  return (
    <div>
      <ProjectsPage />
    </div>
  );
};

export default Contact;
